[package]
name = "advent2019"
version = "1.0.0"
authors = ["Ruediger Ludwig <github@savinien.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.23"
regex = "1.4.3"
