[package]
name = "advent2019"
version = "0.1.0"
authors = ["Ruediger Ludwig <github@savinien.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day01 = { path = "../day01" }
day02 = { path = "../day02" }
